name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        run: |
          docker run --rm registry.gitlab.com/professor-rvenson/backend-n1-validate validate

      - name: Print student info
        run: |
          echo "Student ID: ${{ env.STUDENT_ID }}"
          echo "Student Name: ${{ env.STUDENT_NAME }}"
