name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      STUDENT_ID: 202222204
      STUDENT_NAME: Suyane Bonfanti dos Santos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate
        run: |
          docker run --rm registry.gitlab.com/professor-rvenson/backend-n1-validate validate

      - name: Print student info
        run: |
          echo "Student ID: $STUDENT_ID"
          echo "Student Name: $STUDENT_NAME"
